Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda security group (outbound to RDS only)
      VpcId: ${param:VPCID}
      # No inbound rules needed for Lambda ENIs
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: ${param:RDSSGID}
