Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda security group (outbound to RDS only)
      VpcId: ${param:VPCID}
      # No inbound rules needed for Lambda ENIs
      SecurityGroupEgress:
        # Allow the Lambda function to reach the RDS DB on 5432
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: ${param:RDSSGID}

        # Allow DNS lookups (required to resolve the RDS hostname)
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0

        # Allow HTTPS (useful for AWS APIs such as Secrets Manager, STS, etc.)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # Add an ingress rule to the existing RDS Security Group so it accepts
  # connections from the Lambda SG.
  RdsIngressFromLambda:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: ${param:RDSSGID}
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId:
        Ref: LambdaSecurityGroup
