version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
      java: corretto17
    commands:
      - |
          set -euo pipefail
          echo "Installing tools..."
          npm i -g serverless@3 aws-cdk
          python -m pip install --upgrade pip

          # Avoid failing npm ci if package-lock.json doesn't exist
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

          echo "Installing Flyway CLI..."
          FLYWAY_VER="${FLYWAY_VER:-10.16.0}"
          curl -L -o /tmp/flyway.tgz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VER}/flyway-commandline-${FLYWAY_VER}-linux-x64.tar.gz"
          tar -xzf /tmp/flyway.tgz -C /tmp
          export PATH="$PATH:/tmp/flyway-${FLYWAY_VER}"
          flyway -v

  pre_build:
    commands:
      - |
          set -euo pipefail
          echo "Stage: ${STAGE:-dev}"
          echo "Region: ${AWS_REGION:-us-east-1}"
          serverless --version
          cdk --version
          python --version
          java -version

          echo "Preparing DB connection for Flyway..."
          # We expect these env vars to be available in CodeBuild environment:
          # DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD
          # (Same names you use in serverless.yml provider.environment)

          : "${DB_HOST:?Missing DB_HOST}"
          : "${DB_PORT:?Missing DB_PORT}"
          : "${DB_NAME:?Missing DB_NAME}"
          : "${DB_USER:?Missing DB_USER}"
          : "${DB_PASSWORD:?Missing DB_PASSWORD}"

          export DB_JDBC_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"

          echo "Running Flyway migrations (auto schemas, no hardcoded names)..."
          flyway \
            -url="${DB_JDBC_URL}" \
            -user="${DB_USER}" \
            -password="${DB_PASSWORD}" \
            -locations="filesystem:flyway/sql" \
            -defaultSchema="public" \
            -table="flyway_schema_history" \
            -baselineOnMigrate=true \
            migrate

  build:
    commands:
      - |
          set -euo pipefail

          echo "0) Install per-Lambda Python dependencies (vendor folders)"
          for svc in src/app/*; do
            if [ -f "$svc/requirements.txt" ]; then
              echo "Installing requirements for $svc ..."
              rm -rf "$svc/vendor"
              mkdir -p "$svc/vendor"
              python -m pip install -r "$svc/requirements.txt" -t "$svc/vendor"
            fi
          done

          echo "1) Deploy Lambda + HTTP API"
          serverless deploy --stage "${STAGE:-dev}" --region "${AWS_REGION:-us-east-1}"

          echo "2) Start Docker daemon (required for CDK Docker assets)"
          id || true
          ls -l /var/run || true
          ls -l /var/run/docker.sock || true

          nohup dockerd --host=unix:///var/run/docker.sock >/tmp/dockerd.log 2>&1 &
          sleep 4
          tail -n 120 /tmp/dockerd.log || true

          docker info

          echo "3) Deploy ECS/CDK"
          cd infra/cdk
          python -m pip install -r requirements.txt
          cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION:-us-east-1}"
          cdk deploy --all --require-approval never
          cd ../..

artifacts:
  files:
    - "**/*"
