version: 0.2

env:
  variables:
    STAGE: "dev"
    AWS_REGION: "us-east-1"

    RUN_MIGRATIONS: "true"

    RUN_CDK_BOOTSTRAP: "false"

cache:
  paths:
    - 'node_modules/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.npm/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
      java: corretto17
    commands:
      - |
          set -euo pipefail
          echo "Installing tools..."
          npm i -g serverless@3 aws-cdk
          python -m pip install --upgrade pip

          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

          if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
            echo "Installing Flyway CLI..."
            FLYWAY_VER="${FLYWAY_VER:-10.16.0}"
            curl -L -o /tmp/flyway.tgz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VER}/flyway-commandline-${FLYWAY_VER}-linux-x64.tar.gz"
            tar -xzf /tmp/flyway.tgz -C /tmp
            export PATH="$PATH:/tmp/flyway-${FLYWAY_VER}"
            flyway -v
          else
            echo "Skipping Flyway install (RUN_MIGRATIONS=false)"
          fi

  pre_build:
    commands:
      - |
          set -euo pipefail
          echo "Stage: ${STAGE:-dev}"
          echo "Region: ${AWS_REGION:-us-east-1}"
          serverless --version
          cdk --version
          python --version
          java -version

          if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
            echo "Preparing DB connection for Flyway (ENV only)..."

            : "${DB_HOST:?Missing DB_HOST}"
            : "${DB_PORT:?Missing DB_PORT}"
            : "${DB_NAME:?Missing DB_NAME}"
            : "${DB_USER:?Missing DB_USER}"
            : "${DB_PASSWORD:?Missing DB_PASSWORD}"

            export DB_JDBC_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"

            echo "Running Flyway migrations..."
            flyway \
              -url="${DB_JDBC_URL}" \
              -user="${DB_USER}" \
              -password="${DB_PASSWORD}" \
              -locations="filesystem:flyway/sql" \
              -defaultSchema="public" \
              -table="flyway_schema_history" \
              -baselineOnMigrate=true \
              migrate
          else
            echo "Skipping Flyway migrations (RUN_MIGRATIONS=false)"
          fi

  build:
    commands:
      - |
          set -euo pipefail
          echo "0) Install per-Lambda Python dependencies (vendor folders)"
          for svc in src/app/example_api src/app/print_lambda; do
            if [ -f "$svc/requirements.txt" ]; then
              echo "Installing requirements for $svc ..."
              rm -rf "$svc/vendor"
              mkdir -p "$svc/vendor"
              python -m pip install -r "$svc/requirements.txt" -t "$svc/vendor"
            fi
          done

          echo "1) Deploy Lambda + HTTP API"
          serverless deploy --stage "${STAGE:-dev}" --region "${AWS_REGION:-us-east-1}"

          echo "2) Docker info (CodeBuild already provides Docker daemon)"
          docker info

          echo "3) Deploy ECS/CDK"
          cd infra/cdk
          python -m pip install -r requirements.txt
          if [ "${RUN_CDK_BOOTSTRAP:-false}" = "true" ]; then
            cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION:-us-east-1}"
          else
            echo "Skipping cdk bootstrap (RUN_CDK_BOOTSTRAP=false)"
          fi
          cdk deploy --all --require-approval never
          cd ../..

artifacts:
  files:
    - "**/*"
