version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - |
          set -euo pipefail
          echo "Installing tools..."
          npm i -g serverless@3 aws-cdk
          python -m pip install --upgrade pip
          npm ci || npm i

  pre_build:
    commands:
      - |
          set -euo pipefail
          echo "Stage: ${STAGE:-dev}"
          echo "Region: ${AWS_REGION:-us-east-1}"
          serverless --version
          cdk --version
          python --version

  build:
    commands:
      - |
          set -euo pipefail

          echo "1) Deploy Lambda + HTTP API"
          serverless deploy --stage "${STAGE:-dev}" --region "${AWS_REGION:-us-east-1}"

          echo "2) Start Docker daemon (required for CDK Docker assets)"
          nohup dockerd >/tmp/dockerd.log 2>&1 &
          sleep 5
          docker info

          echo "3) Deploy ECS/CDK"
          cd infra/cdk
          python -m pip install -r requirements.txt
          cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION:-us-east-1}"
          cdk deploy --all --require-approval never
          cd ../..

artifacts:
  files:
    - "**/*"
