version: 0.2

env:
  shell: bash
  variables:
    STAGE: "dev"
    AWS_REGION: "us-east-1"
    RUN_MIGRATIONS: "true"
    RUN_CDK_BOOTSTRAP: "false"
    FLYWAY_VER: "10.16.0"

cache:
  paths:
    - "node_modules/**/*"
    - "/root/.cache/pip/**/*"
    - "/root/.npm/**/*"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.9
      java: corretto11
    commands:
      - |
        set -euo pipefail

        echo "== Tool versions =="
        node -v && npm -v
        python --version
        java -version

        echo "== Installing global tools =="
        # Pin Serverless v3 to avoid v4 engine issues
        npm i -g serverless@3 aws-cdk
        python -m pip install --upgrade pip

        echo "== Installing project dependencies =="
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm i
        fi

        if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
          echo "== Installing Flyway CLI locally =="
          mkdir -p .tools

          curl -fSL -o /tmp/flyway.tgz \
            "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VER}/flyway-commandline-${FLYWAY_VER}-linux-x64.tar.gz"

          echo "Downloaded:" && ls -lh /tmp/flyway.tgz

          echo "Validating archive..."
          tar -tzf /tmp/flyway.tgz >/dev/null

          # Avoid SIGPIPE with pipefail: write listing to a file, then read first line
          tar -tzf /tmp/flyway.tgz > /tmp/flyway.list
          FLYWAY_DIR="$(awk -F/ 'NR==1{print $1}' /tmp/flyway.list)"

          echo "Extracting to .tools/${FLYWAY_DIR} ..."
          tar -xzf /tmp/flyway.tgz -C .tools

          export FLYWAY_HOME="${CODEBUILD_SRC_DIR}/.tools/${FLYWAY_DIR}"
          chmod +x "${FLYWAY_HOME}/flyway" || true
          export PATH="${PATH}:${FLYWAY_HOME}"

          echo "Flyway location: ${FLYWAY_HOME}"
          "${FLYWAY_HOME}/flyway" -v
        else
          echo "Skipping Flyway install (RUN_MIGRATIONS=false)"
        fi

  pre_build:
    commands:
      - |
        set -euo pipefail

        echo "Stage: ${STAGE}"
        echo "Region: ${AWS_REGION}"

        serverless --version
        cdk --version

        # Optional: load CI defaults (only if file exists)
        if [ -f .env.ci ]; then
          echo "Loading .env.ci ..."
          set -a
          # shellcheck disable=SC1091
          source .env.ci
          set +a
        fi

        echo "== Docker check (needed for CDK docker assets) =="
        if ! docker info >/dev/null 2>&1; then
          echo "Docker not ready - trying to start..."
          (sudo service docker start || sudo systemctl start docker || true) >/dev/null 2>&1
          for i in 1 2 3 4 5; do
            sleep 2
            docker info >/dev/null 2>&1 && break
          done
        fi

        docker info >/dev/null 2>&1 || { echo "ERROR: Docker not available. Ensure Privileged mode = ON"; exit 1; }

        if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
          echo "== Running Flyway migrations =="
          : "${DB_HOST:?Missing DB_HOST}"
          : "${DB_PORT:?Missing DB_PORT}"
          : "${DB_NAME:?Missing DB_NAME}"
          : "${DB_USER:?Missing DB_USER}"
          : "${DB_PASSWORD:?Missing DB_PASSWORD}"

          export DB_JDBC_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"

          flyway \
            -url="${DB_JDBC_URL}" \
            -user="${DB_USER}" \
            -password="${DB_PASSWORD}" \
            -locations="filesystem:flyway/sql" \
            -defaultSchema="public" \
            -table="flyway_schema_history" \
            -baselineOnMigrate=true \
            migrate
        else
          echo "Skipping migrations (RUN_MIGRATIONS=false)"
        fi

  build:
    commands:
      - |
        set -euo pipefail

        echo "== Install per-Lambda Python deps (vendor) =="
        for svc in src/app/example_api src/app/print_lambda; do
          if [ -f "$svc/requirements.txt" ]; then
            echo "Installing requirements for $svc ..."
            rm -rf "$svc/vendor"
            mkdir -p "$svc/vendor"
            python -m pip install -r "$svc/requirements.txt" -t "$svc/vendor"
          fi
        done

        echo "== 1) Serverless deploy =="
        serverless deploy --stage "${STAGE}" --region "${AWS_REGION}"

        echo "== 2) CDK deploy =="
        cd infra/cdk

        AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
        export CDK_DEFAULT_ACCOUNT="${AWS_ACCOUNT_ID}"
        export CDK_DEFAULT_REGION="${AWS_REGION}"

        echo "Account: ${AWS_ACCOUNT_ID}"
        echo "Region:  ${AWS_REGION}"

        # Clean output folders to avoid recursion/path explosion
        rm -rf cdk.out
        rm -rf ../cdk.out || true

        python -m pip install -r requirements.txt

        if [ "${RUN_CDK_BOOTSTRAP:-false}" = "true" ]; then
          cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION}"
        else
          echo "Skipping cdk bootstrap (RUN_CDK_BOOTSTRAP=false)"
        fi

        cdk deploy --all --require-approval never
        cd ../..

artifacts:
  files:
    - "**/*"
