version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - |
          set -e
          echo "Installing tools..."
          npm i -g serverless@3 aws-cdk
          python -m pip install --upgrade pip
          npm ci || npm i

  pre_build:
    commands:
      - |
          set -e
          echo "Stage: ${STAGE}"
          echo "Region: ${AWS_REGION}"
          serverless --version
          cdk --version
          python --version

  build:
    commands:
      - |
          set -e
          echo "1) Deploy Lambda + HTTP API"
          serverless deploy --stage "${STAGE}" --region "${AWS_REGION}"

          echo "2) Deploy ECS/CDK (privileged mode required)"
          cd infra/cdk
          cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION}"
          cdk deploy DlmEcsStack --require-approval never
          cd ../..

artifacts:
  files:
    - "**/*"
