version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - |
          set -euo pipefail
          echo "Installing tools..."
          npm i -g serverless@3 aws-cdk
          python -m pip install --upgrade pip
          npm ci || npm i

  pre_build:
    commands:
      - |
          set -euo pipefail
          echo "Stage: ${STAGE:-dev}"
          echo "Region: ${AWS_REGION:-us-east-1}"
          serverless --version
          cdk --version
          python --version

  build:
    commands:
      - |
          set -euo pipefail

          echo "0) Install per-Lambda Python dependencies (vendor folders)"
          # Each Lambda folder under src/app/<service>/ owns its own requirements.txt.
          # We install them into src/app/<service>/vendor so Serverless can package them.
          for svc in src/app/*; do
            if [ -f "$svc/requirements.txt" ]; then
              echo "Installing requirements for $svc ..."
              rm -rf "$svc/vendor"
              mkdir -p "$svc/vendor"
              python -m pip install -r "$svc/requirements.txt" -t "$svc/vendor"
            fi
          done

          echo "1) Deploy Lambda + HTTP API"
          serverless deploy --stage "${STAGE:-dev}" --region "${AWS_REGION:-us-east-1}"

          echo "2) Start Docker daemon (required for CDK Docker assets)"
          echo "== Privileged checks =="
          id || true
          ls -l /var/run || true
          ls -l /var/run/docker.sock || true

          nohup dockerd --host=unix:///var/run/docker.sock >/tmp/dockerd.log 2>&1 &
          sleep 4
          echo "== dockerd log =="
          tail -n 120 /tmp/dockerd.log || true

          echo "== docker info =="
          docker info

          echo "3) Deploy ECS/CDK"
          cd infra/cdk
          python -m pip install -r requirements.txt
          cdk bootstrap "aws://${AWS_ACCOUNT_ID}/${AWS_REGION:-us-east-1}"
          cdk deploy --all --require-approval never
          cd ../..


artifacts:
  files:
    - "**/*"
