version: 0.2

env:
  shell: bash
  variables:
    STAGE: "dev"
    AWS_REGION: "us-east-1"
    RUN_MIGRATIONS: "true"
    RUN_CDK_BOOTSTRAP: "false"

cache:
  paths:
    - 'node_modules/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.npm/**/*'


phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.9
      java: corretto11
    commands:
      - set -euo pipefail
      - echo "Installing tools..."
      - node -v && npm -v
      - npm i -g serverless aws-cdk
      - python -m pip install --upgrade pip

      - |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm i
        fi

      - |
        if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
          echo "Installing Flyway CLI (local tool dir)..."
          FLYWAY_VER="${FLYWAY_VER:-10.16.0}"
          mkdir -p .tools
          curl -fSL -o /tmp/flyway.tgz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VER}/flyway-commandline-${FLYWAY_VER}-linux-x64.tar.gz"

          echo "Downloaded /tmp/flyway.tgz:" && ls -lh /tmp/flyway.tgz
          echo "Validating archive..." && tar -tzf /tmp/flyway.tgz >/dev/null

          # avoid SIGPIPE with pipefail:
          tar -tzf /tmp/flyway.tgz > /tmp/flyway.list
          tar -xzf /tmp/flyway.tgz -C .tools
          FLYWAY_DIR=$(head -1 /tmp/flyway.list | cut -d/ -f1)

          export FLYWAY_HOME="$CODEBUILD_SRC_DIR/.tools/${FLYWAY_DIR}"
          chmod +x "${FLYWAY_HOME}/flyway" || true
          export PATH="$PATH:${FLYWAY_HOME}"

          echo "Java:" && java -version
          echo "Flyway:" && flyway -v
        else
          echo "Skipping Flyway install (RUN_MIGRATIONS=false)"
        fi

  pre_build:
    commands:
      - set -euo pipefail
      - echo "Stage: ${STAGE:-dev}"
      - echo "Region: ${AWS_REGION:-us-east-1}"
      - serverless --version
      - cdk --version

  build:
    commands:
      - set -euo pipefail
      - echo "Run your deploy commands here (serverless deploy / cdk deploy ...)"
