FROM public.ecr.aws/lambda/python:3.8

COPY app/print_lambda/requirements.txt .
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY app/print_lambda/print_lambda.py ${LAMBDA_TASK_ROOT}

CMD ["print_lambda.handler"]
